name: Build Minesweeper GUI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore Minesweeper.sln

    - name: Build solution
      run: msbuild Minesweeper.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: Minesweeper.exe
        path: |
          Minesweeper/Release/Minesweeper.exe
